name: Bug Report
description: Create a bug report
labels: [Bug]

body:
  - type: textarea
    attributes:
        label: Describe the bug
        description: A clear and concise description of what the bug is
    validations:
        required: true
      

  - type: textarea
    attributes:
        label: To Reproduce
        description: Steps to reproduce the behaviour
        placeholder: |
          1. Go to '...'
          2. Click on '....'
          3. Scroll down to '....'
          4. See error
    validations:
        required: true
          

  - type: textarea
    attributes:
        label: Expected behavior
        description: A clear and concise description of what you expected to happen.
    validations:
        required: true
    
  - type: input
    attributes:
        label: Device Model
        description: Your device model (e.g., Pixel 7 Pro, Samsung Galaxy S23)
        placeholder: "e.g., Pixel 7 Pro"
    validations:
        required: true

  - type: input
    attributes:
        label: Android Version
        description: Your Android version (e.g., Android 14, Android 15)
        placeholder: "e.g., Android 14"
    validations:
        required: true

  - type: input
    attributes:
        label: KernelSU Version
        description: Your KernelSU version number
        placeholder: "e.g., v0.7.6 or build number"
    validations:
        required: true

  - type: input
    attributes:
        label: Kernel Version
        description: The kernel version you're using from this repository
        placeholder: "e.g., android14-6.1.57-2024-09"
    validations:
        required: true

  - type: input
    attributes:
        label: SUSFS Version
        description: Your SUSFS version
        placeholder: "e.g., v1.5.11"
    validations:
        required: true

  - type: dropdown
    attributes:
        label: Build Variant
        description: Which build variant are you using?
        options:
          - Normal
          - Module Check Bypass
    validations:
        required: true

  - type: checkboxes
    attributes:
        label: Root Method
        description: How did you obtain root access?
        options:
          - label: KernelSU (this kernel)
          - label: Magisk
          - label: Other (specify in additional context)
    validations:
        required: true
    
  - type: textarea
    attributes:
        label: Screenshots
        description: If applicable, add screenshots to help explain your problem.
        
        
  - type: textarea
    attributes:
        label: Logs
        description: If applicable, add crash logs, dmesg output, or any other relevant logs.
        placeholder: |
          Please include relevant logs such as:
          - KernelSU logs
          - dmesg output
          - Logcat output
          - SUSFS logs
        

  - type: textarea
    attributes:
        label: Additional context
        description: Add any other context about the problem here, including any modules installed, custom configurations, etc.
