name: Bug Report
description: Create a bug report
labels: [Bug]

body:
  - type: textarea
    attributes:
        label: Describe the bug
        description: A clear and concise description of what the bug is
    validations:
        required: true
      

  - type: textarea
    attributes:
        label: To Reproduce
        description: Steps to reproduce the behaviour
        placeholder: |
          1. Go to '...'
          2. Click on '....'
          3. Scroll down to '....'
          4. See error
    validations:
        required: true
          

  - type: textarea
    attributes:
        label: Expected behavior
        description: A clear and concise description of what you expected to happen.
    validations:
        required: true
    
  - type: input
    attributes:
        label: Device Model
        description: Your device model
        placeholder: "e.g., Google Pixel 8"
    validations:
        required: true

  - type: input
    attributes:
        label: Android Version
        description: Your Android version
        placeholder: "e.g., Android 16"
    validations:
        required: true

  - type: input
    attributes:
        label: Stock Kernel Version
        description: The original kernel version on your device
        placeholder: "e.g., 6.1.134-android14"
    validations:
        required: true

  - type: input
    attributes:
        label: Kernel Flashed Version
        description: The kernel version you flashed
        placeholder: "e.g., 6.1.134-android14"
    validations:
        required: true

  - type: input
    attributes:
        label: WKSU Kernel Version
        description: Your WKSU kernel version number
        placeholder: "e.g., 13971"
    validations:
        required: true

  - type: input
    attributes:
        label: Manager
        description: Which KernelSU manager you're using
        placeholder: "e.g., Wild KSU"
    validations:
        required: true

  - type: input
    attributes:
        label: Manager Version
        description: Your manager version
        placeholder: "e.g., v0.0.165(13974)"
    validations:
        required: true

  - type: input
    attributes:
        label: Release Flashed
        description: Which release version you flashed
        placeholder: "e.g., v1.5.12-r2"
    validations:
        required: true

  - type: checkboxes
    attributes:
        label: Tried Both Normal and Module Bypass
        description: Have you tested both build variants?
        options:
          - label: "Yes, I have tried both Normal and Module Check Bypass variants"
          - label: "No, I have only tried one variant (specify which in additional context)"
    validations:
        required: true
    
  - type: textarea
    attributes:
        label: Screenshots
        description: If applicable, add screenshots to help explain your problem.
        
        
  - type: textarea
    attributes:
        label: Logs
        description: If applicable, add crash logs, dmesg output, or any other relevant logs.
        placeholder: |
          Please include relevant logs such as:
          - KernelSU logs
          - dmesg output
          - Logcat output
          - SUSFS logs
        

  - type: textarea
    attributes:
        label: Additional context
        description: Add any other context about the problem here, including any modules installed, custom configurations, etc.
