name: Kernel Config - A12 5.10

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:

jobs:
  build-kernels-a12:
    strategy:
      fail-fast: false
      matrix:
        include:
        - sub_level: "168"
          os_patch_level: "2023-04"
        - sub_level: "198"
          os_patch_level: "2024-01"
        - sub_level: "205"
          os_patch_level: "2024-03"
        - sub_level: "209"
          os_patch_level: "2024-05"
        - sub_level: "218"
          os_patch_level: "2024-08"
        - sub_level: "226"
          os_patch_level: "2024-11"
        - sub_level: "233"
          os_patch_level: "2025-02"
        - sub_level: "236"
          os_patch_level: "2025-05"
        - sub_level: "237"
          os_patch_level: "2025-06"
        - sub_level: "240"
          os_patch_level: "2025-09"
        - sub_level: "X"
          os_patch_level: "lts"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android12"
      kernel_version: "5.10"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}

