name: Sync to GitLab

permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Sync to GitLab
      uses: keninkujovic/gitlab-sync@2.1.0
      with:
        gitlab_url: https://gitlab.com/TheWildJames/${{ github.event.repository.name }}.git
        username: TheWildJames
        gitlab_pat: ${{ secrets.GITLAB_PAT }}
        force_push: true